title: Portfolio of projects
description: Welcome to the online portfolio of machine learning and simulation projects by Hamid Ebadi
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ebadi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: hamidebadi #if your site has a twitter account, enter it here

# Author Settings
author: Hamid Ebadi # add your name
author-img: hamid-ebadi.jpg # add your photo
about-author: PhD in Computer Science from Chalmers University of Technology, Sweden
social-twitter: hamidebadi # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: ebadi # add your Github handle
social-linkedin: hamidebadi # add your Linkedin handle
social-email: hamid[dot]ebadi(a)gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
