title: Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the online portfolio of machine learning work by Hamid Ebadi
permalink: ':title/'
baseurl: "/ebadi.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: hamidebadi #if your site has a twitter account, enter it here

# Author Settings
author: Hamid Ebadi # add your name
author-img: hamid-ebadi.jpg # add your photo
about-author: Ph.D in computer science.
. # add description
social-twitter: hamidebadi # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: ebadi # add your Github handle
social-linkedin: hamidebadi # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
