version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    command: jekyll serve --watch --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
      - "35729:35729"   # LiveReload port
    volumes:
      - .:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle   # cache gems between restarts
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_bundle:
